# Generated by Django 6.0.2 on 2026-03-07 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoImportacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_importacion', models.DateTimeField(auto_now_add=True)),
                ('total_registros', models.IntegerField(default=0)),
                ('procesados', models.IntegerField(default=0)),
                ('recategorizados', models.IntegerField(default=0)),
                ('sin_cambios', models.IntegerField(default=0)),
                ('no_aptos', models.IntegerField(default=0)),
                ('anomalias', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'resultado_importacion',
                'ordering': ['-fecha_importacion'],
            },
        ),
        migrations.CreateModel(
            name='ClienteNoApto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuenta_contrato', models.CharField(max_length=50)),
                ('instalacion', models.CharField(max_length=50)),
                ('tarifa_referencia', models.CharField(blank=True, max_length=20, null=True)),
                ('observacion', models.TextField()),
                ('porcion', models.CharField(blank=True, max_length=50, null=True)),
                ('unidad_predial', models.CharField(blank=True, max_length=50, null=True)),
                ('meses_en_ventana', models.FloatField(blank=True, null=True)),
                ('estado_inicial', models.CharField(blank=True, max_length=50, null=True)),
                ('importacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes_no_aptos', to='operaciones.resultadoimportacion')),
            ],
            options={
                'db_table': 'clientes_no_aptos',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instalacion', models.CharField(max_length=50)),
                ('cuenta_contrato', models.CharField(max_length=50)),
                ('total_dias_consumo', models.FloatField(default=0)),
                ('total_consumo', models.FloatField(default=0)),
                ('promedio_diario', models.FloatField(default=0)),
                ('promedio_mensual', models.FloatField(default=0)),
                ('tarifa_anterior', models.CharField(max_length=20)),
                ('tarifa_nueva', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=20)),
                ('porcion', models.CharField(blank=True, max_length=50, null=True)),
                ('unidad_predial', models.CharField(blank=True, max_length=50, null=True)),
                ('importacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='operaciones.resultadoimportacion')),
            ],
            options={
                'db_table': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='Anomalia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuenta_contrato', models.CharField(max_length=50)),
                ('instalacion', models.CharField(max_length=50)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('tipo_anomalia', models.TextField()),
                ('importacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalias_lista', to='operaciones.resultadoimportacion')),
            ],
            options={
                'db_table': 'anomalias',
            },
        ),
        migrations.CreateModel(
            name='ResumenTarifario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarifa_anterior', models.CharField(max_length=20)),
                ('tarifa_nueva', models.CharField(max_length=20)),
                ('cantidad_clientes', models.IntegerField(default=0)),
                ('porcentaje', models.FloatField(default=0)),
                ('importacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumenes', to='operaciones.resultadoimportacion')),
            ],
            options={
                'db_table': 'resumen_tarifario',
            },
        ),
    ]
