# Generated by Django 6.0.2 on 2026-03-12 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0002_resultadoimportacion_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumoMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuenta_contrato', models.CharField(max_length=50)),
                ('instalacion', models.CharField(max_length=50)),
                ('porcion', models.CharField(blank=True, max_length=50, null=True)),
                ('periodo', models.CharField(max_length=7)),
                ('consumo', models.FloatField(default=0)),
                ('dias', models.IntegerField(default=0)),
                ('tarifa', models.CharField(blank=True, max_length=20, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consumos_mensuales', to='operaciones.cliente')),
                ('importacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos_mensuales', to='operaciones.resultadoimportacion')),
            ],
            options={
                'db_table': 'consumo_mensual',
                'ordering': ['periodo'],
                'indexes': [models.Index(fields=['importacion', 'periodo'], name='consumo_men_importa_87c2ec_idx'), models.Index(fields=['importacion', 'porcion'], name='consumo_men_importa_4808a9_idx')],
            },
        ),
    ]
