# Generated by Django 6.0.2 on 2026-03-30 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0003_consumomensual'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='rango_consumo',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
