# Generated by Django 6.0.2 on 2026-03-31 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0004_cliente_rango_consumo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatrizRecategorizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuenta_contrato', models.CharField(max_length=50)),
                ('instalacion', models.CharField(max_length=50)),
                ('porcion', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_tarifa', models.CharField(blank=True, max_length=20, null=True)),
                ('cf_mes_historico', models.FloatField(blank=True, null=True)),
                ('fl_mes_historico', models.DateField(blank=True, null=True)),
                ('cl_mes_historico', models.FloatField(blank=True, null=True)),
                ('cf_mes_1', models.FloatField(blank=True, null=True)),
                ('fl_mes_1', models.DateField(blank=True, null=True)),
                ('dc_mes_1', models.FloatField(blank=True, null=True)),
                ('cl_mes_1', models.FloatField(blank=True, null=True)),
                ('tarifa_mes_1', models.CharField(blank=True, max_length=20, null=True)),
                ('cf_mes_2', models.FloatField(blank=True, null=True)),
                ('fl_mes_2', models.DateField(blank=True, null=True)),
                ('dc_mes_2', models.FloatField(blank=True, null=True)),
                ('cl_mes_2', models.FloatField(blank=True, null=True)),
                ('tarifa_mes_2', models.CharField(blank=True, max_length=20, null=True)),
                ('cf_mes_3', models.FloatField(blank=True, null=True)),
                ('fl_mes_3', models.DateField(blank=True, null=True)),
                ('dc_mes_3', models.FloatField(blank=True, null=True)),
                ('cl_mes_3', models.FloatField(blank=True, null=True)),
                ('tarifa_mes_3', models.CharField(blank=True, max_length=20, null=True)),
                ('cf_mes_4', models.FloatField(blank=True, null=True)),
                ('fl_mes_4', models.DateField(blank=True, null=True)),
                ('dc_mes_4', models.FloatField(blank=True, null=True)),
                ('cl_mes_4', models.FloatField(blank=True, null=True)),
                ('tarifa_mes_4', models.CharField(blank=True, max_length=20, null=True)),
                ('cf_mes_5', models.FloatField(blank=True, null=True)),
                ('fl_mes_5', models.DateField(blank=True, null=True)),
                ('dc_mes_5', models.FloatField(blank=True, null=True)),
                ('cl_mes_5', models.FloatField(blank=True, null=True)),
                ('tarifa_mes_5', models.CharField(blank=True, max_length=20, null=True)),
                ('cf_mes_6', models.FloatField(blank=True, null=True)),
                ('fl_mes_6', models.DateField(blank=True, null=True)),
                ('dc_mes_6', models.FloatField(blank=True, null=True)),
                ('cl_mes_6', models.FloatField(blank=True, null=True)),
                ('lectura_anterior', models.FloatField(blank=True, null=True)),
                ('lectura_actual', models.FloatField(blank=True, null=True)),
                ('factor_correccion', models.FloatField(blank=True, null=True)),
                ('total_consumo', models.FloatField(default=0)),
                ('total_dias', models.FloatField(default=0)),
                ('promedio_diario', models.FloatField(default=0)),
                ('promedio_mensual', models.FloatField(default=0)),
                ('promedio_redondeado', models.IntegerField(default=0)),
                ('tarifa_actual', models.CharField(blank=True, max_length=20, null=True)),
                ('tarifa_nueva', models.CharField(blank=True, max_length=20, null=True)),
                ('recategorizar', models.CharField(blank=True, max_length=5, null=True)),
                ('rango_consumo', models.CharField(blank=True, max_length=30, null=True)),
                ('comportamiento', models.CharField(blank=True, max_length=50, null=True)),
                ('importacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriz_recategorizacion', to='operaciones.resultadoimportacion')),
            ],
            options={
                'db_table': 'matriz_recategorizacion',
                'indexes': [models.Index(fields=['importacion', 'instalacion'], name='matriz_reca_importa_d39f8c_idx'), models.Index(fields=['importacion', 'recategorizar'], name='matriz_reca_importa_dc7c41_idx'), models.Index(fields=['importacion', 'porcion'], name='matriz_reca_importa_9e5c0f_idx')],
            },
        ),
    ]
